---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
- name: ubuntu
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[bountiful-test]
